import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import { AppContextProvider } from "@/state/AppContextProvider";
import { HeroSection } from "@/components/Hero";
import { About } from "@/components/About";
import { Portfolio } from "@/components/Portfolio";
import { Contact } from "@/components/Contact";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Dauda Olushola Benedict</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContextProvider>
        <Header />
        <HeroSection />
        <About />
        <Portfolio />
        <Contact />
        <Footer />
      </AppContextProvider>
    </>
  );
}
